In [31]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv('pivotdata.csv')

In [3]:
df

         date      city  temperature  humidity
0  05-01-2017  new york         65.0      56.0
1  05-02-2017  new york         66.0      58.0
2  05-03-2017  new york         68.0      60.0
3  05-01-2017    mumbai         75.0      80.0
4  05-02-2017    mumbai         78.0      83.0
5  05-03-2017    mumbai         82.0      85.0
6  05-01-2017   beijing         80.0      26.0
7  05-02-2017   beijing         77.0      30.0
8  05-03-2017   beijing         79.0      35.0
9         NaN       NaN          NaN       NaN

In [5]:
df.dropna(axis=0, inplace= True )

In [6]:
df.pivot(index= "date", columns= "city")

           temperature                 humidity
city           beijing mumbai new york  beijing mumbai new york
date
05-01-2017        80.0   75.0     65.0     26.0   80.0     56.0
05-02-2017        77.0   78.0     66.0     30.0   83.0     58.0
05-03-2017        79.0   82.0     68.0     35.0   85.0     60.0

In [7]:
df

         date      city  temperature  humidity
0  05-01-2017  new york         65.0      56.0
1  05-02-2017  new york         66.0      58.0
2  05-03-2017  new york         68.0      60.0
3  05-01-2017    mumbai         75.0      80.0
4  05-02-2017    mumbai         78.0      83.0
5  05-03-2017    mumbai         82.0      85.0
6  05-01-2017   beijing         80.0      26.0
7  05-02-2017   beijing         77.0      30.0
8  05-03-2017   beijing         79.0      35.0

In [8]:
df.pivot(index= "date", columns= "city", values= "temperature")

city        beijing  mumbai  new york
date
05-01-2017     80.0    75.0      65.0
05-02-2017     77.0    78.0      66.0
05-03-2017     79.0    82.0      68.0

In [9]:
df.pivot(index= "date", columns= "city", values= "humidity")

city        beijing  mumbai  new york
date
05-01-2017     26.0    80.0      56.0
05-02-2017     30.0    83.0      58.0
05-03-2017     35.0    85.0      60.0

In [10]:
df.pivot_table(index= "city", columns= "date",)

           humidity                       temperature
date     05-01-2017 05-02-2017 05-03-2017  05-01-2017 05-02-2017 05-03-2017
city
beijing        26.0       30.0       35.0        80.0       77.0       79.0
mumbai         80.0       83.0       85.0        75.0       78.0       82.0
new york       56.0       58.0       60.0        65.0       66.0       68.0

In [21]:
df.pivot_table(index= "city", columns= "date",aggfunc= { "temperature": "sum"}) #mean is default aggregation

         temperature
date      05-01-2017 05-02-2017 05-03-2017
city
beijing         80.0       77.0       79.0
mumbai          75.0       78.0       82.0
new york        65.0       66.0       68.0

In [36]:
df.pivot_table(index= "city", columns= "date",aggfunc= { "temperature": "count", "humidity":"sum"})

           humidity                       temperature
date     2017-05-01 2017-05-02 2017-05-03  2017-05-01 2017-05-02 2017-05-03
city
beijing        26.0       30.0       35.0           1          1          1
mumbai         80.0       83.0       85.0           1          1          1
new york       56.0       58.0       60.0           1          1          1

In [27]:
type(df['date'][0])

str

In [28]:
df['date']= pd.to_datetime(df['date'])

In [29]:
type(df['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [1]:
df.pivot_table(index= pd.Grouper(freq = "M", key= "date"), columns = "city")

NameError: name 'df' is not defined